### ISSUE TITLE
 No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

### ISSUE THREAD

**Issue by rmagomeromdlive** [android-actions/setup-android#282]
I keep encountering this error when running my build.  this is the steps i'm running to setup android and to install the nd

```
- name: Setup Android SDK
   uses: android-actions/setup-android@v2
- name: Install NDK
   run: sdkmanager "ndk;22.0.7026061"
```

How anyone encountered this error before?

**Comment by ViliusSutkus89** [comment]
Your sdkmanager is installed correctly. NDK too, even though it can be auto-installed during gradle build. The problem is somewhere else.

Would guess that maybe you are trying to build for a very early Android API version or something like that. Are you willing to show build log and the project's gradle.build ?

**Comment by ViliusSutkus89** [comment]
Also, NDK-22 is already unsupported.
23.1.7779620 is LTS,
24.0.8215888 is current.
